### ISSUE TITLE
Simulated Crash Data Not Showing on Dashboard

### ISSUE THREAD

**Issue by jermahs** [emilyemorehouse/cordova-plugin-rollbar#3]
I have an older cordova application (not ionic/angular) just plain old JS using some legacy jquery-mobile stuff. I followed your instructions to capture the crash reports with this plugin and even used the simulate crash, but the data isn't showing up in my dashboard. 

There aren't any error outputs or discernible issues when running the application. The simulate crash does crash the app, but doesn't _seem_ to report anything. 

Any help/advice would be appreciated.

**Comment by jermahs** [comment]
Furthermore, I actually experienced a crash with a known click stream and that didn't show up either.

**Comment by emilyemorehouse** [comment]
Hey @jpgilchrist, I'm happy to help if you're still in need.

If so, check out the newest release and make sure you're running on a physical device and not a simulator and make sure you open the app back up after the crash so it can send up the log.

**Comment by jermahs** [comment]
I will not have the time to check on this anytime soon... thus I'll close it for now.
